### ISSUE TITLE
Possible unnecessary memory consumption

### ISSUE THREAD

**Issue by Khatskevich** [Aiven-Open/astacus#141]
I am trying to make a backup on low disk space. I just have 400Mb on the device and around 8Gb diff from previous clickhouse backup.

During the backup I see the following logs
```
  astacus[4058]: INFO        astacus.common.utils        request put local:5515/backup/6/sub-result by NodeOp.send_result
  astacus[4058]: INFO        astacus.common.op        upload.37 status Status.running -> Status.done
  astacus[4058]: INFO        astacus.common.progress        done 0/14 handled, 14 failures, finished
  astacus[4058]: INFO        astacus.common.progress        upload_failure a6fd4cf215a3ac56dab4cee8994e8101324970930286934ecdccd35faf38cc9e 1 -> 0/14 handled, 14 failures
  astacus[4058]: INFO        astacus.common.progress        upload_failure db9a6aae7453c2e73fdc6cf4d6d8c1ad294e32dd2b6af3d80be5f97beaa8c381 1 -> 0/14 handled, 12 failures
  astacus[4058]: astacus.common.exceptions.RohmuException
  astacus[4058]:     raise exceptions.RohmuException from ex
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/astacus/common/rohmustorage.py", line 176, in _f
  astacus[4058]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  astacus[4058]:     return self._upload_key_from_file(key, f)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/astacus/common/rohmustorage.py", line 276, in upload_hexdigest_from_file
  astacus[4058]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  astacus[4058]:     upload_result = storage.upload_hexdigest_from_file(hexdigest, f)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/astacus/node/uploader.py", line 51, in _upload_hexdigest_in_thread
  astacus[4058]: Traceback (most recent call last):
  astacus[4058]: The above exception was the direct cause of the following exception:
  astacus[4058]: OSError: [Errno 28] No space left on device
  astacus[4058]:     self.next_fp.write(enc_data)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/rohmu/encryptor.py", line 123, in write
  astacus[4058]:     self.next_fp.write(data)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/rohmu/zstdfile.py", line 30, in close
  astacus[4058]:     with file_writer(
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/rohmu/rohmufile.py", line 177, in write_file
  astacus[4058]:     rohmufile.write_file(
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/astacus/common/rohmustorage.py", line 233, in _upload_key_from_file
  astacus[4058]:            ^^^^^^^^^^^^^
  astacus[4058]:     return fun(*a, **kw)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/astacus/common/rohmustorage.py", line 172, in _f
  astacus[4058]: Traceback (most recent call last):
  astacus[4058]: During handling of the above exception, another exception occurred:
  astacus[4058]: OSError: [Errno 28] No space left on device
  astacus[4058]:     self.next_fp.write(enc_data)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/rohmu/encryptor.py", line 123, in write
  astacus[4058]:     self.next_fp.write(compressed_data)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/rohmu/zstdfile.py", line 38, in write
  astacus[4058]:     fp_out.write(input_data)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/rohmu/rohmufile.py", line 197, in write_file
  astacus[4058]: Traceback (most recent call last):
  astacus[4058]: ERROR        astacus.node.uploader        Exception uploading PosixPath('/srv/clickhouse_data/shadow/astacus/store/6ca/6ca6408d-2103-4842-ae08-2d8834>
  astacus[4058]: astacus.common.exceptions.RohmuException
  astacus[4058]:     raise exceptions.RohmuException from ex
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/astacus/common/rohmustorage.py", line 176, in _f
  astacus[4058]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  astacus[4058]:     return self._upload_key_from_file(key, f)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/astacus/common/rohmustorage.py", line 276, in upload_hexdigest_from_file
  astacus[4058]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  astacus[4058]:     upload_result = storage.upload_hexdigest_from_file(hexdigest, f)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/astacus/node/uploader.py", line 51, in _upload_hexdigest_in_thread
  astacus[4058]: Traceback (most recent call last):
  astacus[4058]: The above exception was the direct cause of the following exception:
  astacus[4058]: OSError: [Errno 28] No space left on device
  astacus[4058]:     self.next_fp.write(enc_data)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/rohmu/encryptor.py", line 123, in write
  astacus[4058]:     self.next_fp.write(data)
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/rohmu/zstdfile.py", line 30, in close
  astacus[4058]:     with file_writer(
  astacus[4058]:   File "/usr/lib/python3.11/site-packages/rohmu/rohmufile.py", line 177, in write_file
```

As I understand, Astacus should just encrypt and send over the network new clickhouse blocks.

It looks like it needs to make a copy of the file to be sent, consuming extra disk space.
If so - would it be possible to process large files "on the fly", without consuming extra space?

**Comment by kmichel-aiven** [comment]
Hi. Yes, it's possible, this was fixed recently in release 0.16 : https://github.com/Aiven-Open/astacus/compare/0.6.15...0.6.16 :slightly_smiling_face:
